export const products = [
  {
    id: 1,
    name: "chicken",
    type: "makanan",
    description: "Makanan ayam dengan bumbu padang",
    harga: 15000,
    image: require("../assets/images/steak.png"),
    favorite: false,
  },
  {
    id: 2,
    name: "chicken",
    type: "makanan",
    description: "Makanan ayam dengan bumbu padang",
    harga: 15000,
    image: require("../assets/images/steak.png"),
    favorite: false,
  },
  {
    id: 3,
    name: "chicken",
    type: "makanan",
    description: "Makanan ayam dengan bumbu padang",
    harga: 15000,
    image: require("../assets/images/steak.png"),
    favorite: false,
  },
  {
    id: 4,
    name: "Minummmm",
    type: "minuman",
    description: "Makanan ayam dengan bumbu padang",
    harga: 15000,
    image: require("../assets/images/steak.png"),
    favorite: false,
  },
  {
    id: 5,
    name: "Minummmm",
    type: "minuman",
    description: "Makanan ayam dengan bumbu padang",
    harga: 15000,
    image: require("../assets/images/steak.png"),
    favorite: false,
  },
  {
    id: 6,
    name: "chicken",
    type: "makanan",
    description: "Makanan ayam dengan bumbu padang",
    harga: 15000,
    image: require("../assets/images/steak.png"),
    favorite: false,
  },
  {
    id: 7,
    name: "cemilan chicken",
    type: "cemilan",
    description: "Makanan ayam dengan bumbu padang",
    harga: 15000,
    image: require("../assets/images/steak.png"),
    favorite: false,
  },
  {
    id: 8,
    name: "cemilan chicken",
    type: "cemilan",
    description: "Makanan ayam dengan bumbu padang",
    harga: 15000,
    image: require("../assets/images/steak.png"),
    favorite: false,
  },
  {
    id: 9,
    name: "cemilan chicken",
    type: "cemilan",
    description: "Makanan ayam dengan bumbu padang",
    harga: 15000,
    image: require("../assets/images/steak.png"),
    favorite: false,
  },
];
